app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_home.scss
app/views/shared/_navbar.html.erb

modified:   app/assets/stylesheets/components/_navbar.scss
modified:   app/views/shared/_navbar.html.erb

Layout Home Adjustements, Logo Adjustments

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Home adjustments

---

app/views/pages/home.html.erb

added video do cloudinary and home page is working normally and rails server is no longer stalling whith ctrl+c

video now working from cloudinary

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_footer.html.erb

modified:   app/views/shared/_footer.html.erb

Home info review

---

app/views/experiences/index.html.erb
app/views/shared/_search.html.erb
db/schema.rb
db/seeds.rb

modified:   app/views/experiences/index.html.erb
modified:   app/views/shared/_search.html.erb
modified:   db/schema.rb
modified:   db/seeds.rb

search form created and routed for presentation

---

app/views/pages/home.html.erb
config/environments/production.rb

image tag added to three font page images... 
-          <%= image_tag ('ballet_home.jpg') %>
+          <%= cl_image_tag ("ballet_home") %>
-          <%= image_tag ('chez_why.jpg') %>
+          <%= cl_image_tag ("chez_why") %>
-          <%= image_tag ('skate_why.jpg') %>
+          <%= cl_image_tag ("skate_why") %>
some minor home page text changes... 
and >>
-  config.assets.compile = false
+  config.assets.compile = true

image cldnry tags added

---

app/assets/stylesheets/pages/_match.scss
app/views/experiences/show.html.erb

Carousel enabled

---

app/models/booking.rb
app/models/category.rb
app/models/experience.rb
app/models/supplier.rb
app/models/user.rb
db/seeds.rb

corrected the models to enable destroy function during seed to all has_many relations.
still have to input the seed file with all the data of suppliers'

new seed file and corrected models

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/layouts/_cards.scss
app/assets/stylesheets/pages/_home.scss
app/views/shared/_card.html.erb
db/schema.rb

1. "Manual Flip Enablement - Smartphone UX"
modified:   Gemfile
modified:   Gemfile.lock
modified:   app/assets/javascripts/application.js
modified:   app/assets/stylesheets/layouts/_cards.scss
modified:   app/views/shared/_card.html.erb
modified:   db/schema.rb
2."Card Layout Media Query partial Solution"
modified:   app/assets/stylesheets/layouts/_cards.scss
modified:   app/views/shared/_card.html.erb

Card manual flip smartphone touch

---

db/seeds.rb

5 diving suppliers and 5 diving experiences
5 yoga just as above
2 pilates old rigged... will do them next

seeds for diving and yoga ready - pilates still to go

---

db/seeds.rb

cloudinary tags working inside seeds

---

app/assets/stylesheets/components/_navbar.scss
app/assets/stylesheets/pages/_match.scss
app/views/experiences/show.html.erb
app/views/shared/_card.html.erb

Match Page - Navbar + Footer + banner + Grid:
modified:   app/assets/stylesheets/components/_navbar.scss
modified:   app/assets/stylesheets/components/_navbar.scss
modified:   app/views/shared/_card.html.erb

Match Page - Navbar + Footer + banner + Grid

---

app/assets/stylesheets/pages/_match.scss
app/views/experiences/show.html.erb

banner adjustments, renaming dashboard css to not affect cards:

banner adjustments, renaming dashboard css to not affect cards

---

app/assets/stylesheets/pages/_match.scss
app/helpers/application_helper.rb
app/views/experiences/show.html.erb
app/views/layouts/application.html.erb

NavBar and Footer Application Helper Method + Match Page Main layout adjustment:
modified:   app/helpers/application_helper.rb
modified:   app/views/layouts/application.html.erb

NavBar and Footer Helper Statement + Match Page Main layout adjustment

---

app/assets/stylesheets/pages/_match.scss
app/javascript/packs/skrollr.js
app/views/experiences/show.html.erb
package.json
yarn.lock

Scroll JS at Match Page - Temporarly Disabled (commented):
new file:    app/javascript/packs/skrollr.js
modified:   package.json
modified:   yarn.lock

Scroll JS at Match Page - Temporarly Disabled (commented)

---

app/assets/stylesheets/layouts/_signup.scss

css update color
new file:   app/assets/stylesheets/layouts/_signup.scss

css update color

---

app/assets/stylesheets/pages/_match.scss
app/views/experiences/show.html.erb

V1 Final Layout Match page

---

app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_match.scss
app/views/experiences/show.html.erb

Layout Match Page - Map + Chat + If Statement"
modified:   app/assets/stylesheets/config/_bootstrap_variables.scss

Layout Match Page - Map + Chat + If Statement

---

Gemfile
Gemfile.lock
app/assets/javascripts/application.js
app/assets/stylesheets/application.scss
app/assets/stylesheets/config/_bootstrap_variables.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_match.scss
app/controllers/bookings_controller.rb
app/views/bookings/new.html.erb
app/views/experiences/show.html.erb
app/views/pages/home.html.erb
config/initializers/social_share_button.rb

"Match Page css fixes:
modified:   Gemfile
modified:   Gemfile.lock
modified:   app/assets/javascripts/application.js
modified:   app/assets/stylesheets/application.scss
modified:   app/assets/stylesheets/config/_bootstrap_variables.scss
modified:   app/controllers/bookings_controller.rb
modified:   app/views/bookings/new.html.erb
new file:   config/initializers/social_share_button.rb

Match Page css fixes

---

app/assets/stylesheets/pages/_booking_confirmation.scss
app/views/bookings/new.html.erb

Booking Modal/Page CSS and HTML fixes
modified:   app/assets/stylesheets/pages/_booking_confirmation.scss
modified:   app/views/bookings/new.html.erb

Booking Modal/Page CSS and HTML fixes

---

app/assets/stylesheets/pages/_home.scss
app/javascript/packs/application.js
app/views/pages/home.html.erb

"Steps Trybes - New Home Banner"
modified:   app/javascript/packs/application.js

Steps Trybes - New Home Banner

---

app/assets/stylesheets/application.scss
app/assets/stylesheets/pages/_home.scss
app/assets/stylesheets/pages/_index.scss
app/javascript/packs/application.js
app/views/pages/home.html.erb

"Banner Carousel Promoters Home Page"
modified:   app/assets/stylesheets/application.scss
modified:   app/assets/stylesheets/pages/_index.scss
modified:   app/javascript/packs/application.js

Banner Carousel Promoters Home Page

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb
app/views/shared/_navbar.html.erb

Navbar Contact Us Modal Setup"
modified:   app/views/shared/_navbar.html.erb
"Home Promoter Media Query Smartphone Correction"

Home promoters

---

app/assets/stylesheets/pages/_match.scss
app/assets/stylesheets/pages/_user_profile.scss
app/views/bookings/user_bookings.html.erb
app/views/experiences/show.html.erb

"Match Banner/Show Correction"
"Match Dashboard Experience Description Media Query Padding" 
Partial solution Profile page"
modified:   app/assets/stylesheets/pages/_user_profile.scss
modified:   app/views/bookings/user_bookings.html.erb
"Card-profile style in the Profile Page"
modified:   app/assets/stylesheets/pages/_user_profile.scss
modified:   app/views/bookings/user_bookings.html.erb

Profile banner scss

---

app/assets/stylesheets/pages/_booking_confirmation.scss
app/views/bookings/new.html.erb

"Booking confirmation SCSS fixes"
modified:   app/assets/stylesheets/pages/_booking_confirmation.scss
modified:   app/views/bookings/new.html.erb

Booking confirmation SCSS fixes

---

app/assets/stylesheets/pages/_home.scss
app/views/pages/home.html.erb

Banner Promoters Image 1280 Clousinary fixe"

Banner Promoters Image 1280 Clousinary fixe

---

app/assets/stylesheets/layouts/_cards.scss
app/assets/stylesheets/pages/_home.scss

"Card Cover & Img Max-Heigh 200px+ Home Trybes Flow color change"
modified:   app/assets/stylesheets/layouts/_cards.scss

Card Cover & Img Max-Heigh 200px+ Home Trybes Flow color change
